# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dfa46af76868dc6ae767d296ffb3e9e63039f2ea9e3c02a4a3e38732156736528537b846e33d0111cbee8717ece4f08d3359d1789a529caceb0c7df274aa5d6d

test:
  secret_key_base: 2426165ad6c57dae0693b8c4127ea82aebdc3f162dacac4d42b7f1c8df9bc27df4454021b3e9c31ec03d8fa3f32b6eaee062bd5f7e3a3c4ae9ddee0604dae8c2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
